#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

# Window Configuration

bspc config border_width         3
bspc config window_gap          12

bspc config split_ratio          0.6
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# Window Rules

bspc rule -a Gimp follow=on
bspc rule -a Screenkey manage=off
bspc rule -a St state=floating

# Autostart
~/.config/bspwm/autostart.sh
